### ISSUE TITLE
`stakker_macros` linked from website doesn't exist

### ISSUE THREAD

**Issue by d4h0** [uazu/stakker#19]
Hi,

I just noticed, that the [website](https://uazu.github.io/stakker/) links to [stakker_macros](https://crates.io/crates/stakker_macros), which doesn't exist.

**Comment by joseluis** [comment]
I think there's been recently several updates to the documentation that links to unpublished changes... 

I noticed yesterday too that the linked [ActorOwnSlab](https://uazu.github.io/stakker/d-nodetach.html) in the guide doesn't exist yet either.

**Comment by uazu** [comment]
Thanks for noticing. `stakker_macros` was an experiment which is not going to be published soon. It was using procedural macros to simplify the signatures of actor methods. I'm in two minds about whether it's an improvement. Whenever procedural macros are involved, it means magic is going on that the coder can't see (unlike `macro_rules!` macros). I'll take that off the page for now.

`ActorOwnSlab` will be published very soon! I need to finish testing it. When I pushed the docs update I forgot that it linked to stuff that wasn't up there yet. Also the `query!` macro is in the same position. (One of the issues is that link-checking tools don't seem to work against docs.rs, so I can't be sure all the docs.rs links are valid without clicking them.)

I'll resolve this issue when the links are all correct.

**Comment by uazu** [comment]
I think this is resolved now. `ActorOwnSlab` needed a few revisions before I was happy with it. Please re-open if there are still any issues with links. However I think it is fixed now.
