### ISSUE TITLE
Can not initialise actor using fully qualified init method

### ISSUE THREAD

**Issue by TmLev** [uazu/stakker#20]
With the following code
```rust
let thing = actor!(
    stakker,
    some_crate::Struct::init(),
    ret_nop!()
);
```

Compiler fails with error:
```
error: no rules expected the token `::`
  --> tests/test.rs:37:35
   |
37 |             some_crate::Struct::init(),
   |                               ^^ no rules expected this token in macro call
```

I assume that the `actor!` macro does not expect anything apart from the struct's name and method, which is quite limiting.

**Comment by uazu** [comment]
You need: `<some_crate::Struct>::init()`. There is an example in the documentation for `actor!`. Perhaps it is not obvious enough?

As far as I can see, this is a limitation of the parsing rules for `macro_rules!`. I couldn't find a way to allow you to write it in a natural way. If I write `$type:ty`, that cannot be followed by a `::` ([see here](https://doc.rust-lang.org/reference/macros-by-example.html#follow-set-ambiguity-restrictions)).

If trying with `<...>` works, and reviewing the docs it seems clear enough, then please close this. If you can think of a better way to do this in `macro_rules!` let me know. If you think Stakker needs better documentation in this area, then let me know what would be helpful and I'll see about putting the changes in. Thanks.

**Comment by TmLev** [comment]
Oh, sorry -- I've been using stakker without the documentation for some time now, forgot to look there.
Thanks for your quick response.
